learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),
]
# sdfgsafsfd

learning_logs/urls.py
"""Определяет схемы URL для lerning_logs"""
from django.urls import path  # Импортирует функцию path из модуля django.urls, необходимую для создания URL-схем.
from . import views  # Импортирует модуль views из текущего пакета (текущего каталога), содержащий представления Django.

app_name = 'learning_logs'  # Задает префикс для пространства имен URL, обеспечивая уникальность для данного приложения.
urlpatterns = [
    path('', views.index, name='index'),  # домашняя страница. Определяет URL-шаблон для домашней страницы. При обращении к корневому URL вызывается представление index из модуля views. Присваивает имени 'index'.
    path('topics/', views.topics, name='topics'),  # страница topics
    path('topic/<int:topic_id>/', views.topic, name='topic'),  # страница topic
    path('new_topic/', views.new_topic, name='new_topic'),  # страница new_topic
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),  # страница new_entry
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),  # страница edit_entry
]

users/urls.py
"""Определени схемы URL для поьзователей"""
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    #Включить URL авторизации по умолчанию
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

learning_logs/models.py
from django.db import models  # Импорт модуля models из Django
from django.contrib.auth.models import User
class Topic(models.Model):  # Определение модели Topic - представляет собой тему, которую изучает пользователь
    """Тема, которую изучает пользователь"""  # Документационная строка для класса
    text = models.CharField(max_length=200)  # Поле для текста темы (максимум 200 символов)
    date_added = models.DateTimeField(auto_now_add=True)  # Поле для даты добавления (автоматически устанавливается при создании)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):  # Метод для строкового представления объекта модели - возвращает текст темы
        """Возвращает строковое представление модели."""
        return self.text  # Возвращает текст темы
class Entry(models.Model):  # Определение модели Entry - представляет собой информацию, изученную пользователем по теме
    """Информация изученная пользователем по теме"""  # Документационная строка для класса
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)  # Внешний ключ к модели Topic (поле где выпадет спискок созданных Topic)
    text = models.TextField()  # Поле для текста записи (неограниченной длины)
    date_added = models.DateTimeField(auto_now_add=True)  # Поле для даты добавления (автоматически устанавливается при создании)
    class Meta:  # Внутренний класс для метаданных модели
        verbose_name_plural = 'entries'  # Название модели во множественном числе для административного интерфейса
    def __str__(self):  # Метод для строкового представления объекта модели - возвращает первые 50 символов текста записи с многоточием
        """Возвращает строковое представление модели."""  # Документационная строка для метода
        if len(self.text)>50:
            return f"{self.text[:50]}..."  # Возвращает первые 50 символов текста записи с многоточием
        else:
            return f"{self.text}"  # Возвращает текст записи

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}
class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': 'Entry:'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render, redirect  # Импортирует функцию render из модуля django.shortcuts для рендеринга шаблонов.
from django.contrib.auth.decorators import login_required
from django.http import Http404
from .models import Topic, Entry  # Импортирует модель Topic из текущего пакета (текущего каталога).
from .forms import TopicForm, EntryForm
def index(request):
    """Домашняя страница приложения Learning Log"""
    return render(request, 'learning_logs/index.html')  # Возвращает ответ на запрос, используя шаблон 'learning_logs/index.html'.
@login_required
def topics(request):
    """Список тем, страница topics"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')  # Получает все объекты Topic из базы данных, упорядоченные по дате добавления.
    context = {'topics': topics}  # Создает контекст с темами для передачи в шаблон.
    return render(request, 'learning_logs/topics.html', context)  # Возвращает ответ на запрос, используя шаблон 'learning_logs/topics.html' и переданный контекст.
@login_required
def topic(request, topic_id):
    """Выводит одну тему и все ее записи"""
    topic = Topic.objects.get(id=topic_id)  # Получает объект Topic из базы данных по его идентификатору.
    if topic.owner !=request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')  # Получает все связанные записи (Entry) для данной темы и упорядочивает их по дате добавления.
    context = {'topic':topic, 'entries':entries}  # Создает контекст с выбранной темой и ее записями для передачи в шаблон.
    return render(request, 'learning_logs/topic.html', context)  # Возвращает ответ на запрос, используя шаблон 'learning_logs/topic.html' и переданный контекст.
@login_required
def new_topic(request):
    """Определяет новую форму"""
    if request.method != 'POST':  # Если запрос не POST, возвращает пустую форму.
        form = TopicForm()
    else:
        form = TopicForm(data=request.POST) # Отправлены данные POST, обработать данные
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            form.save()
            return redirect('learning_logs:topics')
    context = {'form':form} # Вывести пустую или недействительную форму
    return render(request, 'learning_logs/new_topic.html', context)
@login_required
def new_entry(request, topic_id):
    """Определяет новую запись в теме"""
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':  # Если запрос не POST, возвращает пустую форму.
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)  # Отправлены данные POST, обработать данные
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            form.save()
            return redirect('learning_logs:topic', topic_id=topic_id)

    context = {'topic': topic, 'form': form}  # Вывести пустую или недействительную форму
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Редактирует существующую запись"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner !=request.user:
        raise Http404
    if request.method!= 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)
    context = {'entry':entry,'topic':topic,'form':form} #Вывести пустую или недействительную форму
    return render(request, 'learning_logs/edit_entry.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """Регистрирует нового пользователя"""
    if request.method != 'POST':
        # Отображает пустую форму
        form = UserCreationForm()
    else:
        # Обрабатывает отправленную форму
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('learning_logs:index')
    # Вывести пустую или недействительную форму
    context = {'form': form}
    return render(request, 'registration/register.html', context)

learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>
{% load bootstrap4 %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Learning log</title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
      <a class="navbar-brand" href="{% url 'learning_logs:index'%}">Learning Log</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span></button>

      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'learning_logs:topics'%}">Topics</a></li>
        </ul>
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <li class="nav-item">
              <span class="navbar-text">Hello, {{ user.username }}.</span>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:logout'%}">Log out</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:register'%}">Register</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:login'%}">Log in</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <main role="main" class="container">
      <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
      </div>
      <div>
        {% block content %}{% endblock content %}
      </div>
    </main>
</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %} <!-- Расширение шаблона базового HTML-документа -->
{% load bootstrap4 %} <!-- Начало блока контента, который будет вставлен в базовый шаблон -->
{% block page_header %}
    <p><a href="{% url 'learning_logs:topic' topic.id %}"> {{ topic }} </a></p> <!-- Вывод названия темы -->
{% endblock page_header %}
{% block content %} <!-- Начало блока контента, который будет вставлен в базовый шаблон -->
    <p class="lead">Edit entry</p>
    <form method='post' action="{% url 'learning_logs:edit_entry' entry.id %}" class="form">
        {% csrf_token %} <!-- Проверка защиты от CSRF -->
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">save changes</button>
        {% endbuttons %}
    </form> <!-- Завершение формы для добавления новой темы -->
{% endblock content %} <!-- Завершение блока контента -->

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}
{% block page_header %}
    <div class="jambotron">
        <h1 class="display-3">Track your learning</h1>
        <p class="lead">Make your own Learning log, and keep a list of the topics</p>
        <a class="btn btn-lg btn-primary" href="{% url 'users:register'%}" role="button">Register &raquo;</a>
    </div>
{% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %} <!-- Расширение шаблона базового HTML-документа -->
{% load bootstrap4 %} <!-- Начало блока контента, который будет вставлен в базовый шаблон -->
{% block page_header %}
    <p><a href="{% url 'learning_logs:topic' topic.id %}"> {{ topic }} </a></p> <!-- Вывод названия темы -->
{% endblock page_header %}
{% block content %} <!-- Начало блока контента, который будет вставлен в базовый шаблон -->
    <p class="lead">Add a new entry:</p>
    <form method='post' action="{% url 'learning_logs:new_entry' topic.id %}" class="form">
        {% csrf_token %} <!-- Проверка защиты от CSRF -->
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">add entry</button>
        {% endbuttons %}
    </form> <!-- Завершение формы для добавления новой темы -->
{% endblock content %} <!-- Завершение блока контента -->

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %} <!-- Расширение шаблона базового HTML-документа -->
{% load bootstrap4 %} <!-- Начало блока контента, который будет вставлен в базовый шаблон -->
{% block page_header %}
    <h3>Add new topic</h3> <!-- Вывод названия темы -->
{% endblock page_header %}
{% block content %} <!-- Начало блока контента, который будет вставлен в базовый шаблон -->
    <form method="post" action = "{% url 'learning_logs:new_topic' %}" class="form">
        {% csrf_token %} <!-- Проверка защиты от CSRF -->
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">add topic</button>
        {% endbuttons %}
        <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
    </form> <!-- Завершение формы для добавления новой темы -->
{% endblock content %} <!-- Завершение блока контента -->

learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %} <!-- Расширение шаблона базового HTML-документа -->
{% block page_header %}
    <h3>{{ topic }}</h3> <!-- Вывод названия темы -->
{% endblock page_header %}
{% block content %} <!-- Начало блока контента, который будет вставлен в базовый шаблон -->
    <p><a href="{% url 'learning_logs:new_entry' topic.id %}"> add new entry </a></p>
    {% for entry in entries %} <!-- Начало цикла для вывода записей -->
        <div class="card mb-3">
            <h4 class="card-header">
                {{entry.date_added|date:'M d, Y H:i'}}
                <small><a href="{% url 'learning_logs:edit_entry' entry.id %}"> Edit entry </a></small>
            </h4>
            <div class="card-body">
                {{ entry.text|linebreaks }}
            </div>
        </div>
    {% empty %} <!-- Блок, который выполняется, если цикл не содержит элементов -->
        <p>There are no entries</p> <!-- Вывод сообщения, если нет записей -->
    {% endfor %} <!-- Завершение цикла -->
{% endblock content %} <!-- Завершение блока контента -->

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}
{% block page_header %}
    <h1>Topics</h1> <!-- Вывод названия темы -->
{% endblock page_header %}
{% block content %}
    <ul>
        {% for topic in topics %}
            <li><h3>
                <a href="{% url 'learning_logs:topic' topic.id %}"> {{ topic }} </a>
            </h3></li>
        {% empty %}
            <li><h3>No topics have been added yet.</h3></li>
        {% endfor %}
    </ul>
    <h3><a href="{% url 'learning_logs:new_topic' %}"> Add new topic:</a></h3>
{% endblock content %}